

teams = {
'9' : 'Arizona Cardinals',
'88' : 'Arizona Diamondbacks',
'78' : 'Atlanta Braves',
'25' : 'Atlanta Falcons',
'43' : 'Atlanta Hawks',
'63' : 'Baltimore Orioles',
'21' : 'Baltimore Ravens',
'33' : 'Boston Celtics',
'64' : 'Boston Red Socks',
'34' : 'Brooklyn Nets',
'5' : 'Buffalo Bills',
'26' : 'Carolina Panthers',
'44' : 'Charlotte Hornets',
'17' : 'Chicago Bears',
'38' : 'Chicago Bulls',
'83' : 'Chicago Cubs',
'68' : 'Chicago White Sox',
'22' : 'Cincinnati Bengals',
'84' : 'Cincinnati Reds',
'23' : 'Cleveland Browns',
'39' : 'Cleveland Cavaliers',
'69' : 'Cleveland Indians',
'89' : 'Colorado Rockies',
'1' : 'Dallas Cowboys',
'48' : 'Dallas Mavericks',
'13' : 'Denver Broncos',
'53' : 'Denver Nuggets',
'18' : 'Detroit Lions',
'40' : 'Detroit Pistons',
'70' : 'Detroit Tigers',
'58' : 'Golden State Warriors',
'19' : 'Green Bay Packers',
'73' : 'Houston Astros',
'49' : 'Houston Rockets',
'29' : 'Houston Texans',
'41' : 'Indiana Pacers',
'30' : 'Indianapolis Colts',
'31' : 'Jacksonville Jaguars',
'14' : 'Kansas City Chiefs',
'71' : 'Kansas City Royals',
'74' : 'Los Angeles Angels',
'59' : 'Los Angeles Clippers',
'90' : 'Los Angeles Dodgers',
'60' : 'Los Angeles Lakers',
'50' : 'Memphis Grizzlies',
'6' : 'Miami Dolphins',
'45' : 'Miami Heat',
'79' : 'Miami Marlins',
'85' : 'Milwaukee Brewers',
'42' : 'Milwaukee Bucks',
'54' : 'Minnesota Timberwolves',
'72' : 'Minnesota Twins',
'20' : 'Minnesota Vikings',
'7' : 'New England Patriots',
'51' : 'New Orleans Pelicans',
'27' : 'New Orleans Saints',
'2' : 'New York Giants',
'8' : 'New York Jets',
'35' : 'New York Knicks',
'80' : 'New York Mets',
'65' : 'New York Yankee',
'75' : 'Oakland Athletics',
'15' : 'Oakland Raiders',
'55' : 'Oklahoma City Thunder',
'46' : 'Orlando Magic',
'36' : 'Philadelphia 76ers',
'3' : 'Philadelphia Eagles',
'81' : 'Philadelphia Phillies',
'61' : 'Phoenix Suns',
'86' : 'Pittsburgh Pirates',
'24' : 'Pittsburgh Steelers',
'56' : 'Portland Trail Blazers',
'62' : 'Sacramento Kings',
'52' : 'San Antonio Spurs',
'16' : 'San Diego Chargers',
'91' : 'San Diego Padres',
'11' : 'San Francisco 49ers',
'92' : 'San Francisco Giants',
'76' : 'Seattle Mariners',
'12' : 'Seattle Seahawks',
'87' : 'St. Louis Cardinals',
'10' : 'St. Louis Rams',
'28' : 'Tampa Bay Buccaneers',
'66' : 'Tampa Bay Rays',
'32' : 'Tennessee Titans',
'77' : 'Texas Rangers',
'67' : 'Toronto Blue Jays',
'37' : 'Toronto Raptors',
'57' : 'Utah Jazz',
'82' : 'Washington Nationals',
'4' : 'Washington Redskins',
'47' : 'Washington Wizards'
}

players = {
'1' : 'Prince Amukamara',
'2' : 'Robert Ayers',
'3' : 'Cole Beasley',
'4' : 'Jon Beason',
'5': 'Will Beatty',
'6' : 'Odell Beckham Jr.',
'7' : 'Carlos Beltran',
'8' : 'Nat Berhe',
'9' : 'Mackenzy Bernadeau',
'10' : 'Ken Bishop',
'11' : 'Zack Bowman',
#--':'Josh Brent
'12' :'James Brewer',
'13' :'Jay Bromley',
'14':'Charles Brown',
'15':'Stevie Brown',
'16':'Dez Bryant',
'17':'Brandon Carr',
'18':'Bruce Carter',
'19':'Francisco Cervelli',
'20':'Barry Church',
'21':'Morris Claiborne',
'22':'Tyler Clutts',
'23':'Davon Coleman',
'24':'Michael Cox',
'25':'Jack Crawford',
'26':'Tyrone Crawford', 
'27':'Jack Crawford',
'28':'Tyrone Crawford',
'29':'Victor Cruz',
'30':'Zak DeOssie',
'31':'Quintin Demps',
'32':'Larry Donnell',
'33':'Stephen Drew', 
'34':'Lance Dunbar',
'35':'Justin Durant',
'36':'Lavar Edwards',
'37':'Jacoby Ellsbury',
'38':'Gavin Escobar',
'39':'Daniel Fells',
'40':'Chandler Fenner',
'41':'Travis Frederick',
'42':'Doug Free',
'43':'Rogers Gaines', 
'44':'Ben Gardner',
'45':'Brett Gardner', 
'46':'Ben Gardner',
'47':'Jakar Hamilton',
'48':'Johnathan Hankins',
'49':'James Hanna',
'50':'Dwayne Harris',
'51':'Marcus Harris',
'52':'Dwayne Harris',
'53':'Donald Hawkins', 
'54':'Nick Hayden',
'55':'Chase Headley',
'56':'Jeff Heath',
'57':'Mark Herzlich',
'58':'Peyton Hillis',
#--':'Tony Hills':'
'59':'Anthony Hitchens',
'60':'DeVonte Holloman',
'61':'Jayron Hosley',
'62':'Travis Howard',
'63':'David Huff',
'64':'Henry Hynoski',
'65':'Cullen Jenkins',
'66':'Rashad Jennings',
'67':'Jerrel Jernigan',
'68':'John Jerry',
'69':' Derek Jeter', 
'70':'Shawn Kelley',
'71':'Devon Kennard',
'72':'Mathias Kiwanuka', 
'73':'Troy Kropog',
'74':'Markus Kuhn',
'75':'Hiroki Kuroda', 
'76':'L.P. Ladouceur',
'77':'DeMarcus Lawrence', 
'78':'Cameron Lawrence',
'79':'DeMarcus Lawrence',
'80':'Cameron Lawrence',
'81':'Ronald Leary',
'82':'Sean Lee',
'83':'Eli Manning',
'84':'Zack Martin',
'85':'Trumaine McBride',
'86':'Brian McCann',
'87':'Brandon McCarthy', 
'88':'Terrell McClain',
'89':'Rolando McClain',
'90':'Jameel McClain',
'92':'Terrell McClain',
'93':'Rolando McClain',
'94':'Henry Melton',
'95':'Jeremy Mincey',
'96':'Jeremy Mincey',
'97':'Bryan Mitchell',
'98':'Sterling Moore',
'99':'Damontre Moore',
'100':'Sterling Moore',
'101':'Brandon Mosley',
'102':'DeMarco Murray',
'103':'Jordan Najvar',
'104':'Jordan Najvar',
'105':' Ryan Nassib',
'106':'Kevin Ogletree', 
'107':'Preston Parker',
'108':'Jermey Parnell',
'109':'Tyler Patmon',
'110':'Mike Patterson', 
'111':'Spencer Paysinger', 
'112':'Eury Perez',
'113':'David Phelps',
'114':'Jason Pierre-Paul',
'115':'Michael Pineda',
'116':'Jose Pirela',
'117':'Justin Pugh',
'118':'Joseph Randle',
'119':'Rueben Randle',
'120':'Dallas Reynolds',
'121':'Antoan Richardson',
'122':'Weston Richburg',
'123':'David Robertson',
'124':'Adrien Robinson',
'125':'Dominique Rodgers-Cromartie',
'126':'Esmil Rogers',
'127':'Antrel Rolle', 
'128':'Austin Romine',
'129':' Tony Romo',
'130':'Brendan Ryan', 
'131':'John Ryan Murphy',
'132':'Orlando Scandrick',
'133':'Geoff Schwartz',
'134':'George Selvie',
'135':'Tyron Smith',
'136':'Adam Snyder',
'137':'Anthony Spencer',
'138':'C.J. Spillman',
'139':'Devin Street',
'140':'Ichiro Suzuki',
'141':'Masahiro Tanaka',
'142':'Cooper Taylor',
'143':'Mark Teixeira',
'144':'Walter Thurmond III',
'145':'Korey Toomer',
'146':'Dustin Vaughan',
'147':'J.D. Walton',
'148':'Adam Warren',
'149':'Corey Washington',
'150':' Brandon Weeden',
'151':'Darrion Weems',
'152':'Zelous Wheeler',
'153':'Chase Whitley',
'154':'Kyle Wilber',
'155':'Kyle Wilber',
'156':'J.J. Wilcox', 
'157':'Terrance Williams',
'158':'Andre Williams',
'159':'Jacquian William',
'160':'Terrance Williams',
'161':'David Wilson',
'162':'Jason Witten',
'163':'Kerry Wynn',
'164':'Chris Young'
}







